on: push
name: DeployProdSiteOnPush
jobs:
  web-deploy:
    name: ProdDeploy
    runs-on: ubuntu-latest
     if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Get_latest_code
      uses: actions/checkout@v2.3.2
    
    - name: Sync_files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 69.163.197.191
        username: micmcp3
        password: ${{ secrets.FTPASS }}
        server-dir: staggeredcontacts.com/
        local-dir: ./staggeredContacts/
on: push
name: DeployBetaSiteOnPush
jobs:
  web-deploy:
    name: BetaDeploy
    runs-on: ubuntu-latest
     if: ${{ github.ref == 'refs/heads/beta' }}
    steps:
    - name: Get_latest_code
      uses: actions/checkout@v2.3.2
    
    - name: Sync_files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 69.163.197.191
        username: micmcp3
        password: ${{ secrets.FTPASS }}
        server-dir: beta.staggeredcontacts.com/
        local-dir: ./staggeredContacts/
on: push
name: DeployDevSiteOnPush
jobs:
  web-deploy:
    name: DevDeploy
    runs-on: ubuntu-latest
     if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
    - name: Get_latest_code
      uses: actions/checkout@v2.3.2
    
    - name: Sync_files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 69.163.197.191
        username: micmcp3
        password: ${{ secrets.FTPASS }}
        server-dir: dev.staggeredcontacts.com/
        local-dir: ./staggeredContacts/
