on: push
name: DeployDevSiteOnPush
jobs:
  web-deploy:
    if: ${{ github.ref == 'refs/heads/dev' }}
    name: DevDeploy
    runs-on: ubuntu-latest
    steps:
    - name: Get_latest_code
      uses: actions/checkout@v2.3.2
    
    - name: Sync_files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 69.163.197.191
        username: micmcp3
        password: ${{ secrets.FTPASS }}
        server-dir: dev.staggeredcontacts.com/
        local-dir: ./staggeredContacts/
